import { Card } from '.';
import '../styles/Explore.css';

export function Explore({
  isLoggedIn,
  loading,
  currentUser,
  contexts,
  deleteFunc,
}) {
  console.log({ contexts });
  if (!isLoggedIn) {
    return (
      <>
        <h3>user must login to use this feature</h3>
      </>
    );
  }

  if (!Array.isArray(contexts) || contexts.length < 1) {
    return (
      <>
        <div>
          <h3>there are currently no contexts generated by other users</h3>
        </div>
      </>
    );
  }

  return (
    <>
      <div className="explore">
        {contexts.map((context) => {
          return (
            <>
              <Card
                key={context.id}
                id={context.id}
                loading={loading}
                currentUser={currentUser}
                imageUrl={context.imageUrl}
                text={context.text}
                userId={context.userId}
                deleteFunc={deleteFunc}
              />
            </>
          );
        })}
      </div>
    </>
  );
}
